spring:
  application:
    name: mall-gateway
  
  cloud:
    gateway:
      # 全局超时配置
      httpclient:
        connect-timeout: 3000
        response-timeout: 60s
      
      # 全局 CORS 配置
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:3000"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true

# 日志格式（公共）
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] [%X{traceId}] %-5level %logger{36} - %msg%n"

# 白名单（公共）
security:
  whitelist:
    exact:
      - /auth/login
      - /auth/refresh
      - /error
      - /auth/register
    prefix:
      - /actuator/**
jwt:
  secret: mall-secret-key-2024-spring-security-jwt-token